# Generated by Django 4.0.4 on 2024-03-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Pass', models.CharField(max_length=20)),
                ('confpass', models.CharField(max_length=20)),
            ],
        ),
    ]
